instagram_web/blueprints/users/views.py
from models.user import User
from models.follow import Follow
from werkzeug.utils import secure_filename
from werkzeug.security import check_password_hash
from instagram_web.util.google_oauth import oauth
from instagram_web.util.helpers import upload_profile_to_s3
from flask_login import login_required, login_user, logout_user, current_user
from flask import Blueprint, render_template, request, redirect, url_for, flash

users_blueprint = Blueprint('users',
                            __name__,
                            template_folder='templates')

#Sign up page
@users_blueprint.route('/new', methods=['GET'])
def new():
    return render_template('users/new.html')

#Login page
@users_blueprint.route('/loginpage', methods=['GET'])
def loginpage():
    return render_template('users/login.html')

#Requests page
@users_blueprint.route('/requests', methods=['GET'])
def requests():
    follow = Follow.get_or_none(Follow.following == current_user.id)
    return render_template('users/requests.html', follow=follow)

#Google login button
@users_blueprint.route("/google_login")
def google_login():
    redirect_uri = url_for('users.authorize', _external = True)
    return oauth.google.authorize_redirect(redirect_uri)

#Google login page function
@users_blueprint.route("/authorize/google")
def authorize():
    oauth.google.authorize_access_token()
    email = oauth.google.get('https://www.googleapis.com/oauth2/v2/userinfo').json()['email']
    user = User.get_or_none(User.email == email)
    if user:
        login_user(user)
        return redirect(url_for('users.show', username=user.name))
    else:
        return redirect(url_for('users.new'))

#Sign up func
@users_blueprint.route('/', methods=['POST'])
def create():
    new_user = User (
        name = request.form['username'] ,
        email = request.form['email'], 
        password = request.form['password'] 
    )

    if new_user.save():
        flash("Succesfully sign up!")
    else:
        for error in new_user.errors:
            flash(error)
    return redirect(url_for('users.new'))

#Login func
@users_blueprint.route('/login', methods=['POST'])
def login():
    name= request.form.get('username')
    password= request.form.get('password') 

    check_user = User.get_or_none(User.name == name)
    if check_user:
        check_passsword_result= check_password_hash(check_user.password_hash, password)
        if check_passsword_result:
            flash("Succesfully log in!")
            login_user(check_user)
            return redirect(url_for('home'))
        else:
            flash("Login Failure")
            return redirect(url_for('users.loginpage'))
    else:
        flash("No such user")
        return redirect(url_for("users.loginpage"))

#Logout func
@users_blueprint.route('/logout', methods=['POST'])
@login_required
def logout():
    logout_user()
    flash("Succesfully logout!")
    return redirect(url_for('users.loginpage'))

#Follow function
@users_blueprint.route('/follow/<id>', methods=["POST"])
@login_required
def follow(id):

    user = User.get_or_none(User.id == id)

    if user.private_profile == True:
        follow = Follow (
            follower= current_user.id,
            following= user.id
        )
        if follow.save():
            flash(f'Follow request sent to {user.name}!')
        else:
            for error in follow.errors:
                flash(error)
    else:
        follow = Follow (
            follower= current_user.id,
            following= user.id,
            approved= True
        )
        if follow.save():
            flash(f'Succesfully followed {user.name}!')
        else:
            for error in follow.errors:
                flash(error)
    return redirect(url_for('users.show', username=user.name))

#Unfollow function
@users_blueprint.route('/unfollow/<uid>/<id>', methods=["POST"])
@login_required
def unfollow(uid, id):

    user = User.get_or_none(User.id == uid)
    unfollow=Follow.get_by_id(id)

    if unfollow.delete_instance(recursive=True):
        flash("Unfollowed!")
        return redirect(url_for('users.show', username= user.name))
    else:
        flash("Error!")
        return redirect(url_for('users.show', username= user.name))

#Approve function
@users_blueprint.route('/approve/<id>', methods=['POST'])
@login_required
def approve(id):

    approve=Follow(
        id=id, 
        approved=True
    )

    if approve.save(only=[Follow.approved]):
        flash("Approval approved!")
        return redirect(url_for('users.show', username=current_user.name))
    else:
        flash("Error")
        return redirect(url_for('users.show', username=current_user.name))

#User page
@users_blueprint.route('/<username>', methods=["GET"])
@login_required
def show(username):
    user= User.get_or_none(User.name == username)
    if user:
        follow = Follow.get_or_none(Follow.following == user.id)
        return render_template('users/userpage.html', user=user, follow=follow)
    else:
        flash("Please login")
        return redirect(url_for('users.loginpage'))

#Edit User Profile
@users_blueprint.route('/user/<int:id>/edit', methods=["POST"])
@login_required
def edit_info(id):
    
    user = User.get_or_none(User.id == id)
    if user:
        if current_user.id == int(id):
    
            name= request.form.get("edit_name")
            email= request.form.get("edit_email")
            password= request.form.get("edit_password")
            user.private_profile= True if request.form.get("checkbox") == "on" else False
            
            if len(name) > 0:
                user.name = name

            if len(password) > 0:
                user.password = password
            
            if len(email) > 0 :
                user.email = email

            if user.save():
                flash("Details updated")
                return redirect(url_for('users.show', username = user.name))
            else:
                for error in user.errors:
                    flash(error)
                return redirect(url_for('home'))
            

@users_blueprint.route('/', methods=["GET"])
def index():
    return "USERS"

#Edit page
@users_blueprint.route('/<id>/edit', methods=['GET'])
@login_required
def edit(id):
    user = User.get_or_none(User.id == id)
    if user:
        if current_user.id == int(id):
            return render_template('users/editinfo.html', user=user)
    else:
        flash("Please login")
        return redirect(url_for('users.loginpage'))

@users_blueprint.route('/<id>', methods=['POST'])
def update(id):
    pass

#Upload profile image func
@users_blueprint.route('/<id>/upload', methods=['POST'])
@login_required
def upload(id):
    user= User.get_or_none(User.id ==id)
    if user:
        if current_user.id == int(id):
            # Upload Image
            if "user_file" not in request.files:
                flash("No file selected")
                return redirect(url_for('users.show', username=user.name))

            file= request.files["user_file"]

            file.filename = secure_filename(file.filename)

            image_path = upload_profile_to_s3(file, user.name)
            
            user.image_path= image_path

            if user.save():
                flash("Upload sucess!")
                return redirect(url_for('users.show', username=user.name))
            else:
                flash("Upload failed!")
                return redirect(url_for('users.show', username=user.name))
        else:
            flash("Unable to edit other profiles")
            return redirect(url_for('users.show', username=user.name))
    else:
        flash("No such user!")
        return redirect(url_for('home'))
                

instagram_web/blueprints/users/templates/users/editinfo.html
{% extends "_layout.html" %}
{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
  <ul class=flashes>
  {% for message in messages %}
    <li>{{ message }}</li>
  {% endfor %}
  </ul>
{% endif %}
{% endwith %}
{% if current_user.is_authenticated%}
<div class="container-fluid">
  <h2>Update Personal Info</h2>
  <div class="d-flex form-group align-items-center">
    <form class="w-50 m-auto" action="{{ url_for('users.edit_info', id=user.id) }}" method="POST">
        <div class="form-group">
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
          <label for="edit_name">Edit Name:</label>
          <input type='text' name='edit_name' class="form-control mb-2" />
          <label for="edit_email">Edit Email:</label>
          <input type='text' name='edit_email' class="form-control mb-2" />
          <label for="edit_password">Edit Password:</label>
          <input type='text' name='edit_password' class="form-control mb-2" />
          <label for="checkbox">Public / Private Profile:</label>
          <input type='checkbox' name='checkbox' {{'checked' if user.private_profile}} class="form-control mb-2"/>
          <button type="submit" class="btn btn-dark mt-2">Submit</button>
        </div>
    </form>
  </div>
</div>
<hr/>
<div class="container-fluid">
  <div class="d-flex form-group align-items-center">
    <form class="w-50 m-auto" action="{{ url_for('users.upload', id=current_user.id) }}" method="POST" enctype="multipart/form-data">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
      <label for="user_file">Upload Profile Image</label>
      <br></br>
      <input type="file" name="user_file">
      <br></br>
      <button type="submit" class="btn btn-dark">Upload</button>
    </form>
  </div>
</div>
{% endif %}
{% endblock %}

instagram_web/blueprints/users/templates/users/login.html
{% extends "_layout.html" %}

{% block content %}

{% with messages = get_flashed_messages() %}
  {% if messages %}
    <div class=flashes>
      {% for message in messages %}
      <div class="bg-info">{{ message }}</div>
      {% endfor %}
    </div>
  {% endif %}
{% endwith %}
<div class="container-fluid">
<h2>Login Page</h2>
<hr/>
<div class="d-flex form-group">
  <form class="m-auto w-50" action="{{ url_for('users.login') }}" method="POST">
    <div class="form-group">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <div class="m-3">
            <label for="username">Username:</label>
            <input type='text' name='username' class="form-control" />            
        </div>
        <div class="m-3">
            <label for="password">Password:</label>
            <input type='text' name='password' class="form-control" />
        </div>
        <div class="d-flex flex-wrap justify-content-center m-3">
          <button type="submit" class="btn btn-dark m-2">Login</button>
        </div>
    </div>
  </form>
</div>
<hr/>
<form class="text-center" action="{{ url_for('users.google_login') }}">
  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
  <button type="submit" class="btn btn-dark m-2">Login with Google</button>
</form>
</div>
{% endblock %}

instagram_web/blueprints/users/templates/users/new.html
{% extends "_layout.html" %}

{% block content %}

{% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class=flashes>
        {% for message in messages %}
            <div class="bg-info">{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
{% endwith %}

<h3>Sign up Form</h3>
<hr/>
<div class="container-fluid">
    <div class="d-flex form-group">
        <form class ="m-auto w-50" action="{{ url_for('users.create') }}" method="POST">
            <div class="form-group">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                <label for="username">Username:</label>
                <input type='text' name='username' class="form-control mb-2" />            
                <label for="password">Password:</label>
                <input type='text' name='password' class="form-control mb-2" />
                <label for="email">Email address:</label>
                <input type='text' name='email' class="form-control mb-2" />
                <button type="submit" class="btn btn-dark">Sign Up</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

instagram_web/blueprints/users/templates/users/requests.html
{% extends "_layout.html" %}
{% block content %}
<h2>Requests</h2>

<div>Followers:</div>
{% for user in current_user.followers %}
    <span>{{user.follower.name}}</span>
    <form action="{{ url_for('users.unfollow', uid= current_user.id, id=user)}}" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <button type ="submit" class="btn btn-dark m-1"> Remove </button>
    </form>
{% endfor %}
<hr>
<div>Follower requests (pending approvals):</div>
{% for request in current_user.following_requests %}
<p>{{ request.name }}</p>
<form action="{{ url_for('users.approve', id=follow)}}" method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <button type ="submit" class="btn btn-dark m-1"> Approve </button>
</form>
{% endfor %}
<hr>
<div>Following:</div>
{% for user in current_user.followings %}
    <span>{{user.following.name}}</span>
    <form action="{{ url_for('users.unfollow', uid= current_user.id, id=user)}}" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <button type ="submit" class="btn btn-dark m-1"> Unfollow </button>
    </form>
{% endfor %}
<hr>
<div>Following requests (pending approval):</div>
{% for following in current_user.follower_requests %}
<p>{{ following.name }}</p>
<form action="{{ url_for('users.unfollow', uid= current_user.id, id=follow.id)}}" method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <button type ="submit" class="btn btn-dark m-1"> Unfollow </button>
</form>
{% endfor %}
{% endblock %}

instagram_web/blueprints/users/templates/users/userpage.html
{% extends "_layout.html" %}
{% block content %}

{% with messages = get_flashed_messages() %}
  {% if messages %}
    <div class=flashes>
    {% for message in messages %}
      <div class="bg-info">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{% endwith %}

{% if current_user.is_authenticated %}

<div class="container">
  <div class="card col-12 flex-column mt-2">
    <img id="profile_image" class="col-12 align-self-center rounded-circle mt-2 w-50" src="{{ user.profile_image_url }}"/>
    <h3>@{{ user.name }}</h3>
    <p>Description:....</p>

    <div>Followers:</div>
    {% for user in user.followers %}
      <span>{{user.follower.name}}</span>
    {% endfor %}

    <div>Following:</div>
    {% for user in user.followings %}
      <span>{{user.following.name}}</span>
    {% endfor %}

    <br>

    {% if user.private_profile %}
      <p>Private Profile</p>
    {% else %}
      <p>Public Profile</p>
    {% endif %}

    {% if current_user.name == user.name %}
      <div class="d-flex form-group justify-content-center m-0">
        <a class="btn btn-dark m-1" href="{{ url_for('users.edit', id=current_user.id) }}"> Edit Profile </a>
        <a class="btn btn-dark m-1" href="{{ url_for('images.new') }}"> Upload Image </a>
        <a class="btn btn-dark m-1" href="{{ url_for('users.requests')}}">Requests</a>
      </div>
    {% else %}
      {% if follow %}
        <div class="d-flex form-group justify-content-center m-0">
          <form action="{{ url_for('users.unfollow', uid= user.id, id=follow.id) }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <button type ="submit" class="btn btn-dark m-1"> Unfollow </button>
          </form>
        </div>
      {% else %}
        <div class="d-flex form-group justify-content-center m-0">
          <form action="{{ url_for('users.follow', id=user.id) }}" method="POST">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
            <button type ="submit" class="btn btn-dark m-1"> Follow </button>
          </form>
        </div>
      {% endif %}
    {% endif %}
  </div>

  <div class="d-flex flex-row flex-wrap">
  {% if follow.approved or current_user.name == user.name %}
    {% for image in user.images %}
      <div class="card col-lg-4 col-md-6 col-sm-12">
        <img class="card-img-top mt-auto mb-auto p-2" src="{{ image.images_url }}" width="300"/>
      
        <p class="card-text align-self-center"> Total donations received: </p>
        <p class="card-text align-self-center"> $ {{ image.donations| sum(attribute="amount") }}</p>
      
        {% if current_user.name !=user.name %}
          <a class="btn btn-dark align-self-center" href="{{ url_for('images.payment', images_id=image.id) }}"> Donate </a>
        {% endif %}
      </div>
    {% endfor %}
  {% endif %}
  </div>
</div>
{% endif %}
{% endblock %}